// AUTO-GENERATED by crates/akita-sis-estimator/examples/euclidean_width_table.rs -- do not edit by hand.
//
// SIS width thresholds for 128-bit quantum security (ADPS16, Euclidean norm=2).
// Rust estimator path: akita-sis-estimator::euclidean_width_table.
// Keys bound the squared norm of the complete scalar collision vector.

mod q128;
mod q32;
mod q64;

use super::SisModulusProfileId;

/// SHA-256 digest of `audit.csv`, including every accepted boundary and rejected successor.
pub(crate) const TABLE_DIGEST: [u8; 32] = [
    0xa1, 0xcc, 0x0a, 0x06, 0x08, 0x97, 0x44, 0x14, 0x5b, 0x61, 0x91, 0x9c, 0xf0, 0x01, 0xea, 0x26,
    0x0c, 0x95, 0xa4, 0xbb, 0xa1, 0x61, 0xff, 0xda, 0xff, 0x55, 0x39, 0x1d, 0x0d, 0xfa, 0x10, 0x2a,
];

/// Generated SIS max-width table: for each `(family, d, collision_l2_sq)` the
/// maximum secure ring-element width per module rank (`widths[rank - 1]`).
#[rustfmt::skip]
pub(crate) fn sis_max_widths(
    family: SisModulusProfileId,
    d: u32,
    collision_l2_sq: u128,
) -> Option<&'static [u64]> {
    match family {
        SisModulusProfileId::Q32Offset99 => q32::sis_max_widths(d, collision_l2_sq),
        SisModulusProfileId::Q64Offset59 => q64::sis_max_widths(d, collision_l2_sq),
        SisModulusProfileId::Q128OffsetA7F7 => q128::sis_max_widths(d, collision_l2_sq),
    }
}
