// AUTO-GENERATED by crates/akita-sis-estimator/examples/euclidean_width_table.rs -- do not edit by hand.
//
// SIS width thresholds for 128-bit quantum security (ADPS16, Euclidean norm=2).
// Rust estimator path: akita-sis-estimator::euclidean_width_table.
// Keys bound the squared norm of the complete scalar collision vector.

mod q128;
mod q32;
mod q64;

use super::SisModulusProfileId;

/// Generated SIS max-width table: for each `(family, d, collision_l2_sq)` the
/// maximum secure ring-element width per module rank (`widths[rank - 1]`).
#[rustfmt::skip]
pub(crate) fn sis_max_widths(
    family: SisModulusProfileId,
    d: u32,
    collision_l2_sq: u128,
) -> Option<&'static [u64]> {
    match family {
        SisModulusProfileId::Q32Offset99 => q32::sis_max_widths(d, collision_l2_sq),
        SisModulusProfileId::Q64Offset59 => q64::sis_max_widths(d, collision_l2_sq),
        SisModulusProfileId::Q128OffsetA7F7 => q128::sis_max_widths(d, collision_l2_sq),
    }
}
