// AUTO-GENERATED by labinius_infinity_width_table --from-csv -- do not edit by hand.
// Source: crates/akita-sis-estimator/data/labinius_small_modulus_infinity_width.csv

use super::width_table::{LabiniusSmallModulusWidthCell, LabiniusWidthCutoff};
use super::{LabiniusCommitmentModulus, LabiniusRingDegree};

#[rustfmt::skip]
pub const LABINIUS_SMALL_MODULUS_WIDTH_TABLE: &[LabiniusSmallModulusWidthCell] = &[
    LabiniusSmallModulusWidthCell { commitment_modulus: LabiniusCommitmentModulus::Q28Offset2103, ring_degree: LabiniusRingDegree::D648, rank: 3, coeff_linf_bound: 24116880, max_width: 6400000000000, cutoff: LabiniusWidthCutoff::SearchCap },
    LabiniusSmallModulusWidthCell { commitment_modulus: LabiniusCommitmentModulus::Q28Offset2103, ring_degree: LabiniusRingDegree::D648, rank: 4, coeff_linf_bound: 24116880, max_width: 6400000000000, cutoff: LabiniusWidthCutoff::SearchCap },
];

#[rustfmt::skip]
pub const LABINIUS_SMALL_MODULUS_WIDTH_TABLE_DIGEST: [u8; 32] = [236, 130, 120, 53, 51, 167, 78, 138, 145, 177, 149, 21, 187, 249, 227, 195, 106, 144, 174, 208, 79, 25, 40, 214, 148, 19, 11, 45, 120, 207, 77, 231];
