// AUTO-GENERATED by crates/akita-sis-estimator/examples/euclidean_width_table.rs -- do not edit by hand.
//
// SIS width thresholds for 169-bit quantum security (ADPS16, Euclidean norm=2).
// Rust estimator path: akita-sis-estimator::euclidean_width_table.
// Keys bound the squared norm of the complete scalar collision vector.

mod q128;
mod q32;
mod q64;

use super::SisModulusProfileId;

/// SHA-256 digest of the generated audit CSV, including every accepted boundary and rejected successor.
pub(crate) const TABLE_DIGEST: [u8; 32] = [
    0x03, 0x7e, 0xd5, 0x21, 0xe2, 0x72, 0x8a, 0x39, 0x64, 0xfd, 0x61, 0x40, 0x45, 0xe3, 0x19, 0xd2,
    0x89, 0x3c, 0xc8, 0xe4, 0x58, 0x1e, 0x20, 0xca, 0xb2, 0x7a, 0x57, 0xed, 0xec, 0xf5, 0xce, 0xde,
];

/// Generated SIS max-width table: for each `(family, d, collision_l2_sq)` the
/// maximum secure ring-element width per module rank (`widths[rank - 1]`).
#[rustfmt::skip]
pub(crate) fn sis_max_widths(
    family: SisModulusProfileId,
    d: u32,
    collision_l2_sq: u128,
) -> Option<&'static [u64]> {
    match family {
        SisModulusProfileId::Q32Offset99 => q32::sis_max_widths(d, collision_l2_sq),
        SisModulusProfileId::Q64Offset59 => q64::sis_max_widths(d, collision_l2_sq),
        SisModulusProfileId::Q128OffsetA7F7 => q128::sis_max_widths(d, collision_l2_sq),
    }
}
