// AUTO-GENERATED by crates/akita-sis-estimator/examples/infinity_width_table.rs -- do not edit by hand.
//
// SIS max-width tables for Quantum128BitADPS16V2.
// Sole hard gate: ADPS16 quantum LGSA model >= 128 bits.
// Each row records the selected optimizer's accepted cutoff and rejected successor.
// Shape and norm: LGSA, coefficient L-infinity.
// Rust estimator path: akita-sis-estimator::width_table.
// Runtime keys are (d, coefficient-L-infinity bound) -> widths by module rank.
// Values are projected from scalar cutoffs: width[r-1] = cutoff_m(B, n=r*d) / d.
// Optimizer profile: local-minimum+proven-pruned-certification.

mod q128;
mod q32;
mod q64;

use super::{SisModulusProfileId, SisSecurityPolicyId};

/// SHA3-256 identity of the generated table and provenance files.
pub(super) const SIS_TABLE_DIGEST: [u8; 32] = [
    0xf7, 0x3d, 0x9b, 0xd1, 0xce, 0x0e, 0x29, 0xdb, 0xf2, 0x5c, 0x68, 0xec, 0xd6, 0x2e, 0xfc, 0xce,
    0x42, 0x51, 0x56, 0x42, 0x1b, 0x75, 0xbe, 0xa3, 0x80, 0x0b, 0xdc, 0xb2, 0x60, 0xeb, 0x91, 0xca,
];

/// Generated SIS max-width table for the named security policy.
///
/// Runtime keys are `(d, coeff_linf_bound) -> widths[rank - 1]`, projected from
/// scalar cutoffs as `width = cutoff_m(B, n = rank * d) / d`.
#[rustfmt::skip]
pub(crate) fn sis_max_widths(
    policy: SisSecurityPolicyId,
    modulus_profile: SisModulusProfileId,
    d: u32,
    coeff_linf_bound: u128,
) -> Option<&'static [u64]> {
    if policy != SisSecurityPolicyId::Quantum128BitADPS16V2 {
        return None;
    }
    match modulus_profile {
        SisModulusProfileId::Q32Offset99 => q32::sis_max_widths(d, coeff_linf_bound),
        SisModulusProfileId::Q64Offset59 => q64::sis_max_widths(d, coeff_linf_bound),
        SisModulusProfileId::Q128OffsetA7F7 => q128::sis_max_widths(d, coeff_linf_bound),
    }
}
