// AUTO-GENERATED by the SIS quantum scalar table generator.
//
// The runtime artifact is keyed only by the reachable scalar cells
// (coefficient bound B, scalar dimension n). Role and ring-origin provenance
// lives in the coverage certificate and is validated before lookup.

mod q128;
mod q32;
mod q64;

use super::{ScalarCutoff, SisModulusProfileId, SisSecurityPolicyId};

#[rustfmt::skip]
pub(crate) fn sis_scalar_cutoff(
    policy: SisSecurityPolicyId,
    profile: SisModulusProfileId,
    coeff_linf_bound: u128,
    n: u64,
) -> Option<ScalarCutoff> {
    if policy != SisSecurityPolicyId::Quantum128BitADPS16 {
        return None;
    }
    match profile {
        SisModulusProfileId::Q32Offset99 => q32::sis_scalar_cutoff(coeff_linf_bound, n),
        SisModulusProfileId::Q64Offset59 => q64::sis_scalar_cutoff(coeff_linf_bound, n),
        SisModulusProfileId::Q128OffsetA7F7 => q128::sis_scalar_cutoff(coeff_linf_bound, n),
    }
}
