// AUTO-GENERATED by crates/akita-sis-estimator/examples/infinity_width_table.rs -- do not edit by hand.
//
// SIS max-width tables for Quantum128BitADPS16.
// Sole hard gate: ADPS16 quantum LGSA model >= 128 bits.
// Each row records the selected optimizer's accepted cutoff and rejected successor.
// Shape and norm: LGSA, coefficient L-infinity.
// Rust estimator path: akita-sis-estimator::width_table.
// Runtime keys are (d, coefficient-L-infinity bound) -> widths by module rank.
// Values are projected from scalar cutoffs: width[r-1] = cutoff_m(B, n=r*d) / d.
// Optimizer profile: local-minimum+proven-pruned-certification.

mod q128;
mod q32;
mod q64;

use super::{SisModulusProfileId, SisSecurityPolicyId};

/// SHA3-256 identity of the generated table and provenance files.
pub(super) const SIS_TABLE_DIGEST: [u8; 32] = [
    0x3b, 0xed, 0x8e, 0xcc, 0xf2, 0xf0, 0xeb, 0xff, 0xdf, 0x22, 0xd7, 0x87, 0x5e, 0xe4, 0x3b, 0xe2,
    0xfb, 0x6d, 0x35, 0x16, 0x7e, 0x07, 0x3e, 0xe3, 0x9a, 0x66, 0xf5, 0x18, 0xb7, 0x9e, 0x8a, 0x03,
];

/// Generated SIS max-width table for the named security policy.
///
/// Runtime keys are `(d, coeff_linf_bound) -> widths[rank - 1]`, projected from
/// scalar cutoffs as `width = cutoff_m(B, n = rank * d) / d`.
#[rustfmt::skip]
pub(crate) fn sis_max_widths(
    policy: SisSecurityPolicyId,
    modulus_profile: SisModulusProfileId,
    d: u32,
    coeff_linf_bound: u128,
) -> Option<&'static [u64]> {
    if policy != SisSecurityPolicyId::Quantum128BitADPS16 {
        return None;
    }
    match modulus_profile {
        SisModulusProfileId::Q32Offset99 => q32::sis_max_widths(d, coeff_linf_bound),
        SisModulusProfileId::Q64Offset59 => q64::sis_max_widths(d, coeff_linf_bound),
        SisModulusProfileId::Q128OffsetA7F7 => q128::sis_max_widths(d, coeff_linf_bound),
    }
}
