//! AUTO-GENERATED by scripts/stitch_generated_sis_linf_table.py — do not edit by hand.
//!
//! Placeholder until `sage -python scripts/stitch_generated_sis_linf_table.py` completes.

mod q128;
mod q32;
mod q64;

use super::SisModulusFamily;

/// Generated coefficient-Linf SIS max-width table.
#[rustfmt::skip]
pub(crate) fn sis_max_widths(
    family: SisModulusFamily,
    d: u32,
    collision_linf: u128,
) -> Option<&'static [u64]> {
    match family {
        SisModulusFamily::Q32 => q32::sis_max_widths(d, collision_linf),
        SisModulusFamily::Q64 => q64::sis_max_widths(d, collision_linf),
        SisModulusFamily::Q128 => q128::sis_max_widths(d, collision_linf),
    }
}
