use akita_sis_estimator::{
    euclidean_width_table::{
        generate_euclidean_width_rows, rust_table_arms, validate_euclidean_width_rows,
        EuclideanWidthRow, EuclideanWidthTableConfig,
    },
    AkitaModulusFamily,
};
use std::{
    env, fs,
    io::{self, Write},
    path::{Path, PathBuf},
    process,
    time::Instant,
};

const TABLE_HEADER: &str = "// AUTO-GENERATED by crates/akita-sis-estimator/examples/euclidean_width_table.rs -- do not edit by hand.\n//\n// SIS width thresholds for 128-bit security (BDGL16, Euclidean norm=2).\n// Rust estimator path: akita-sis-estimator::euclidean_width_table.\n// Keys are the union of power-of-two squared-collision buckets and derived keys K = d * B^2.\n\n";

#[derive(Debug)]
struct Args {
    config: EuclideanWidthTableConfig,
    output: Option<PathBuf>,
    format: OutputFormat,
    skip_validation: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum OutputFormat {
    Csv,
    RustSplit,
}

fn main() {
    let args = Args::parse_or_exit();
    let t0 = Instant::now();
    let rows = generate_euclidean_width_rows(&args.config)
        .unwrap_or_else(|error| fatal(&format!("width-table generation failed: {error}")));
    if !args.skip_validation {
        validate_euclidean_width_rows(&rows)
            .unwrap_or_else(|error| fatal(&format!("width-table validation failed: {error}")));
    }
    match args.format {
        OutputFormat::Csv => write_csv_rows(&rows, args.output.as_ref())
            .unwrap_or_else(|error| fatal(&format!("failed to write CSV: {error}"))),
        OutputFormat::RustSplit => write_rust_split(&rows, &args.config, args.output.as_deref())
            .unwrap_or_else(|error| fatal(&format!("failed to write Rust table: {error}"))),
    }
    eprintln!(
        "wrote {} euclidean width row(s) in {:.3}s",
        rows.len(),
        t0.elapsed().as_secs_f64()
    );
}

impl Args {
    fn parse_or_exit() -> Self {
        let mut config = EuclideanWidthTableConfig::default();
        let mut output = None;
        let mut format = OutputFormat::Csv;
        let mut skip_validation = false;
        let mut args = env::args().skip(1);
        while let Some(arg) = args.next() {
            match arg.as_str() {
                "--help" | "-h" => usage(0),
                "--skip-validation" => skip_validation = true,
                _ => {
                    let value = args
                        .next()
                        .unwrap_or_else(|| fatal(&format!("missing value for {arg}")));
                    match arg.as_str() {
                        "--output" => output = Some(PathBuf::from(value)),
                        "--format" => format = parse_format(&value),
                        "--families" => config.families = parse_families(&value),
                        "--dims" => config.ring_dims = parse_csv(&value, "--dims"),
                        "--collisions" => {
                            config.collision_l2_sq = parse_csv(&value, "--collisions");
                        }
                        "--max-rank" => config.max_rank = parse(&value, "--max-rank"),
                        "--target-bits" => config.target_bits = parse(&value, "--target-bits"),
                        "--search-cap" => config.search_cap = Some(parse(&value, "--search-cap")),
                        _ => fatal(&format!("unknown argument {arg}")),
                    }
                }
            }
        }
        Self {
            config,
            output,
            format,
            skip_validation,
        }
    }
}

fn write_csv_rows(rows: &[EuclideanWidthRow], output: Option<&PathBuf>) -> io::Result<()> {
    match output {
        Some(path) => {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            let mut file = fs::File::create(path)?;
            write_csv_rows_to(&mut file, rows)
        }
        None => {
            let stdout = io::stdout();
            let mut handle = stdout.lock();
            write_csv_rows_to(&mut handle, rows)
        }
    }
}

fn write_csv_rows_to(mut writer: impl Write, rows: &[EuclideanWidthRow]) -> io::Result<()> {
    writeln!(writer, "{}", EuclideanWidthRow::csv_header())?;
    for row in rows {
        writeln!(writer, "{}", row.to_csv_record())?;
    }
    Ok(())
}

fn write_rust_split(
    rows: &[EuclideanWidthRow],
    config: &EuclideanWidthTableConfig,
    output: Option<&Path>,
) -> io::Result<()> {
    let out_dir =
        output.unwrap_or_else(|| Path::new("crates/akita-types/src/sis/generated_sis_table"));
    fs::create_dir_all(out_dir)?;
    fs::write(out_dir.join("mod.rs"), rust_mod_source())?;
    let arms = rust_table_arms(rows, config.max_rank);
    for family in [
        AkitaModulusFamily::Q32,
        AkitaModulusFamily::Q64,
        AkitaModulusFamily::Q128,
    ] {
        fs::write(
            out_dir.join(format!("{}.rs", family.label())),
            rust_family_source(family, arms.get(&family).map(Vec::as_slice).unwrap_or(&[])),
        )?;
    }
    Ok(())
}

fn rust_mod_source() -> String {
    format!(
        "{TABLE_HEADER}mod q128;\nmod q32;\nmod q64;\n\nuse super::SisModulusFamily;\n\n/// Generated SIS max-width table: for each `(family, d, collision_l2_sq)` the\n/// maximum secure ring-element width per module rank (`widths[rank - 1]`).\n#[rustfmt::skip]\npub(crate) fn sis_max_widths(\n    family: SisModulusFamily,\n    d: u32,\n    collision_l2_sq: u128,\n) -> Option<&'static [u64]> {{\n    match family {{\n        SisModulusFamily::Q32 => q32::sis_max_widths(d, collision_l2_sq),\n        SisModulusFamily::Q64 => q64::sis_max_widths(d, collision_l2_sq),\n        SisModulusFamily::Q128 => q128::sis_max_widths(d, collision_l2_sq),\n    }}\n}}\n"
    )
}

fn rust_family_source(family: AkitaModulusFamily, arms: &[String]) -> String {
    let mut source = format!(
        "{TABLE_HEADER}// Family: {}\n\n#[rustfmt::skip]\npub(super) fn sis_max_widths(d: u32, collision_l2_sq: u128) -> Option<&'static [u64]> {{\n    match (d, collision_l2_sq) {{\n",
        family.label().to_uppercase()
    );
    for arm in arms {
        source.push_str("        ");
        source.push_str(arm);
        source.push('\n');
    }
    source.push_str("        _ => None,\n    }\n}\n");
    source
}

fn parse_families(raw: &str) -> Vec<AkitaModulusFamily> {
    raw.split(',')
        .filter(|value| !value.trim().is_empty())
        .map(|value| {
            AkitaModulusFamily::parse(value.trim())
                .unwrap_or_else(|error| fatal(&format!("invalid --families entry: {error}")))
        })
        .collect()
}

fn parse_csv<T>(raw: &str, field: &str) -> Vec<T>
where
    T: std::str::FromStr,
    T::Err: std::fmt::Debug,
{
    let values: Vec<T> = raw
        .split(',')
        .filter(|value| !value.trim().is_empty())
        .map(|value| parse(value.trim(), field))
        .collect();
    if values.is_empty() {
        fatal(&format!("{field} must not be empty"));
    }
    values
}

fn parse_format(value: &str) -> OutputFormat {
    match value {
        "csv" => OutputFormat::Csv,
        "rust-split" | "rust_split" => OutputFormat::RustSplit,
        _ => fatal("--format must be one of: csv, rust-split"),
    }
}

fn parse<T>(value: &str, field: &str) -> T
where
    T: std::str::FromStr,
    T::Err: std::fmt::Debug,
{
    value
        .parse()
        .unwrap_or_else(|error| fatal(&format!("invalid {field}: {error:?}")))
}

fn usage(code: i32) -> ! {
    eprintln!(
        "usage: euclidean_width_table [--output PATH] [--format csv|rust-split] [--families q32,q64,q128] [--dims 32,64,128,256] [--collisions C1,C2] [--max-rank N] [--target-bits BITS] [--search-cap N] [--skip-validation]"
    );
    process::exit(code);
}

fn fatal(message: &str) -> ! {
    eprintln!("error: {message}");
    process::exit(2);
}
