use akita_sis_estimator::{
    euclidean_width_table::{
        generate_euclidean_width_rows, is_full_euclidean_width_table_config, rust_table_arms,
        validate_euclidean_width_rows, EuclideanWidthRow, EuclideanWidthTableConfig,
    },
    AkitaModulusProfileId,
};
use sha2::{Digest, Sha256};
use std::{
    env,
    fmt::Write as _,
    fs,
    io::{self, Write as _},
    path::{Path, PathBuf},
    process,
    time::Instant,
};

const TABLE_HEADER: &str = "// AUTO-GENERATED by crates/akita-sis-estimator/examples/euclidean_width_table.rs -- do not edit by hand.\n//\n// SIS width thresholds for 128-bit quantum security (ADPS16, Euclidean norm=2).\n// Rust estimator path: akita-sis-estimator::euclidean_width_table.\n// Keys bound the squared norm of the complete scalar collision vector.\n\n";

#[derive(Debug)]
struct Args {
    config: EuclideanWidthTableConfig,
    output: Option<PathBuf>,
    format: OutputFormat,
    skip_validation: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum OutputFormat {
    Csv,
    RustSplit,
}

fn main() {
    let args = Args::parse_or_exit();
    if args.format == OutputFormat::RustSplit && !is_full_euclidean_width_table_config(&args.config)
    {
        fatal(
            "rust-split output requires the complete production table config; use CSV for partial comparison jobs",
        );
    }
    let t0 = Instant::now();
    let rows = generate_euclidean_width_rows(&args.config)
        .unwrap_or_else(|error| fatal(&format!("width-table generation failed: {error}")));
    if !args.skip_validation {
        validate_euclidean_width_rows(&rows)
            .unwrap_or_else(|error| fatal(&format!("width-table validation failed: {error}")));
    }
    match args.format {
        OutputFormat::Csv => write_csv_rows(&rows, args.output.as_ref())
            .unwrap_or_else(|error| fatal(&format!("failed to write CSV: {error}"))),
        OutputFormat::RustSplit => write_rust_split(&rows, &args.config, args.output.as_deref())
            .unwrap_or_else(|error| fatal(&format!("failed to write Rust table: {error}"))),
    }
    eprintln!(
        "wrote {} euclidean width row(s) in {:.3}s",
        rows.len(),
        t0.elapsed().as_secs_f64()
    );
}

impl Args {
    fn parse_or_exit() -> Self {
        let mut config = EuclideanWidthTableConfig::default();
        let mut output = None;
        let mut format = OutputFormat::Csv;
        let mut skip_validation = false;
        let mut args = env::args().skip(1);
        while let Some(arg) = args.next() {
            match arg.as_str() {
                "--help" | "-h" => usage(0),
                "--skip-validation" => skip_validation = true,
                _ => {
                    let value = args
                        .next()
                        .unwrap_or_else(|| fatal(&format!("missing value for {arg}")));
                    match arg.as_str() {
                        "--output" => output = Some(PathBuf::from(value)),
                        "--format" => format = parse_format(&value),
                        "--families" => config.families = parse_families(&value),
                        "--dims" => config.ring_dims = parse_csv(&value, "--dims"),
                        "--collisions" => {
                            config.collision_l2_sq = parse_csv(&value, "--collisions");
                        }
                        "--max-rank" => config.max_rank = parse(&value, "--max-rank"),
                        "--target-bits" => config.target_bits = parse(&value, "--target-bits"),
                        "--search-cap" => config.search_cap = Some(parse(&value, "--search-cap")),
                        _ => fatal(&format!("unknown argument {arg}")),
                    }
                }
            }
        }
        Self {
            config,
            output,
            format,
            skip_validation,
        }
    }
}

fn write_csv_rows(rows: &[EuclideanWidthRow], output: Option<&PathBuf>) -> io::Result<()> {
    let source = csv_source(rows);
    match output {
        Some(path) => {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            let mut file = fs::File::create(path)?;
            file.write_all(source.as_bytes())
        }
        None => {
            let stdout = io::stdout();
            let mut handle = stdout.lock();
            handle.write_all(source.as_bytes())
        }
    }
}

fn csv_source(rows: &[EuclideanWidthRow]) -> String {
    let mut source = String::new();
    writeln!(&mut source, "{}", EuclideanWidthRow::csv_header())
        .expect("writing to String cannot fail");
    for row in rows {
        writeln!(&mut source, "{}", row.to_csv_record()).expect("writing to String cannot fail");
    }
    source
}

fn write_rust_split(
    rows: &[EuclideanWidthRow],
    config: &EuclideanWidthTableConfig,
    output: Option<&Path>,
) -> io::Result<()> {
    let default_out_dir =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../akita-types/src/sis/generated_l2_sis_table");
    let out_dir = output.unwrap_or(default_out_dir.as_path());
    fs::create_dir_all(out_dir)?;
    let audit_source = csv_source(rows);
    let table_digest: [u8; 32] = Sha256::digest(audit_source.as_bytes()).into();
    fs::write(out_dir.join("audit.csv"), audit_source)?;
    fs::write(out_dir.join("mod.rs"), rust_mod_source(table_digest))?;
    let arms = rust_table_arms(rows, config.max_rank);
    for family in [
        AkitaModulusProfileId::Q31Offset19,
        AkitaModulusProfileId::Q32Offset99,
        AkitaModulusProfileId::Q63Offset259,
        AkitaModulusProfileId::Q64Offset59,
        AkitaModulusProfileId::Q128OffsetA7F7,
    ] {
        fs::write(
            out_dir.join(format!("{}.rs", family.label())),
            rust_family_source(family, arms.get(&family).map(Vec::as_slice).unwrap_or(&[])),
        )?;
    }
    Ok(())
}

fn rust_mod_source(table_digest: [u8; 32]) -> String {
    let digest = table_digest
        .chunks(16)
        .map(|chunk| {
            let bytes = chunk
                .iter()
                .map(|byte| format!("0x{byte:02x}"))
                .collect::<Vec<_>>()
                .join(", ");
            format!("    {bytes},")
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "{TABLE_HEADER}mod q128;\nmod q31;\nmod q32;\nmod q63;\nmod q64;\n\nuse super::SisModulusProfileId;\n\n/// SHA-256 digest of the generated audit CSV, including every accepted boundary and rejected successor.\npub(crate) const TABLE_DIGEST: [u8; 32] = [\n{digest}\n];\n\n/// Generated SIS max-width table: for each `(family, d, collision_l2_sq)` the\n/// maximum secure ring-element width per module rank (`widths[rank - 1]`).\n#[rustfmt::skip]\npub(crate) fn sis_max_widths(\n    family: SisModulusProfileId,\n    d: u32,\n    collision_l2_sq: u128,\n) -> Option<&'static [u64]> {{\n    match family {{\n        SisModulusProfileId::Q31Offset19 => q31::sis_max_widths(d, collision_l2_sq),\n        SisModulusProfileId::Q32Offset99 => q32::sis_max_widths(d, collision_l2_sq),\n        SisModulusProfileId::Q63Offset259 => q63::sis_max_widths(d, collision_l2_sq),\n        SisModulusProfileId::Q64Offset59 => q64::sis_max_widths(d, collision_l2_sq),\n        SisModulusProfileId::Q128OffsetA7F7 => q128::sis_max_widths(d, collision_l2_sq),\n    }}\n}}\n"
    )
}

fn rust_family_source(family: AkitaModulusProfileId, arms: &[String]) -> String {
    let mut source = format!(
        "{TABLE_HEADER}// Family: {}\n\n#[rustfmt::skip]\npub(super) fn sis_max_widths(d: u32, collision_l2_sq: u128) -> Option<&'static [u64]> {{\n    match (d, collision_l2_sq) {{\n",
        family.label().to_uppercase()
    );
    for arm in arms {
        source.push_str("        ");
        source.push_str(arm);
        source.push('\n');
    }
    source.push_str("        _ => None,\n    }\n}\n");
    source
}

fn parse_families(raw: &str) -> Vec<AkitaModulusProfileId> {
    raw.split(',')
        .filter(|value| !value.trim().is_empty())
        .map(|value| {
            AkitaModulusProfileId::parse(value.trim())
                .unwrap_or_else(|error| fatal(&format!("invalid --families entry: {error}")))
        })
        .collect()
}

fn parse_csv<T>(raw: &str, field: &str) -> Vec<T>
where
    T: std::str::FromStr,
    T::Err: std::fmt::Debug,
{
    let values: Vec<T> = raw
        .split(',')
        .filter(|value| !value.trim().is_empty())
        .map(|value| parse(value.trim(), field))
        .collect();
    if values.is_empty() {
        fatal(&format!("{field} must not be empty"));
    }
    values
}

fn parse_format(value: &str) -> OutputFormat {
    match value {
        "csv" => OutputFormat::Csv,
        "rust-split" | "rust_split" => OutputFormat::RustSplit,
        _ => fatal("--format must be one of: csv, rust-split"),
    }
}

fn parse<T>(value: &str, field: &str) -> T
where
    T: std::str::FromStr,
    T::Err: std::fmt::Debug,
{
    value
        .parse()
        .unwrap_or_else(|error| fatal(&format!("invalid {field}: {error:?}")))
}

fn usage(code: i32) -> ! {
    eprintln!(
        "usage: euclidean_width_table [--output PATH] [--format csv|rust-split] [--families q32,q64,q128] [--dims 32,64,128,256] [--collisions C1,C2] [--max-rank N] [--target-bits BITS] [--search-cap N] [--skip-validation]"
    );
    process::exit(code);
}

fn fatal(message: &str) -> ! {
    eprintln!("error: {message}");
    process::exit(2);
}
