use akita_sis_estimator::{
    width_table::{
        generate_infinity_width_rows, is_full_infinity_width_table_config, rust_table_arms,
        validate_infinity_width_rows, InfinityWidthProfile, InfinityWidthRow,
        InfinityWidthTableConfig,
    },
    AkitaModulusFamily,
};
use std::{
    env, fs,
    io::{self, Write},
    path::{Path, PathBuf},
    process,
    time::Instant,
};

const TABLE_HEADER: &str = "// AUTO-GENERATED by crates/akita-sis-estimator/examples/infinity_width_table.rs -- do not edit by hand.\n//\n// SIS width thresholds for L-infinity security (ADPS16/LGSA, infinity norm).\n// Rust estimator path: akita-sis-estimator::width_table.\n// Keys are coefficient-L-infinity buckets.\n\n";

#[derive(Debug)]
struct Args {
    config: InfinityWidthTableConfig,
    output: Option<PathBuf>,
    format: OutputFormat,
    skip_validation: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum OutputFormat {
    Csv,
    RustSplit,
}

fn main() {
    let args = Args::parse_or_exit();
    if args.format == OutputFormat::RustSplit {
        if !is_full_infinity_width_table_config(&args.config) {
            fatal(
                "rust-split output requires the complete production table config; use CSV for partial comparison jobs",
            );
        }
        min_security_bits(&args.config)
            .unwrap_or_else(|| fatal("--format rust-split requires integer --target-bits"));
    }
    let t0 = Instant::now();
    let rows = generate_infinity_width_rows(&args.config)
        .unwrap_or_else(|error| fatal(&format!("width-table generation failed: {error}")));
    if !args.skip_validation {
        validate_infinity_width_rows(&rows)
            .unwrap_or_else(|error| fatal(&format!("width-table validation failed: {error}")));
    }
    match args.format {
        OutputFormat::Csv => write_csv_rows(&rows, args.output.as_ref())
            .unwrap_or_else(|error| fatal(&format!("failed to write CSV: {error}"))),
        OutputFormat::RustSplit => write_rust_split(&rows, &args.config, args.output.as_deref())
            .unwrap_or_else(|error| fatal(&format!("failed to write Rust table: {error}"))),
    }
    eprintln!(
        "wrote {} infinity width row(s) in {:.3}s",
        rows.len(),
        t0.elapsed().as_secs_f64()
    );
}

impl Args {
    fn parse_or_exit() -> Self {
        let mut config = InfinityWidthTableConfig::default();
        let mut output = None;
        let mut format = OutputFormat::Csv;
        let mut skip_validation = false;
        let mut args = env::args().skip(1);
        while let Some(arg) = args.next() {
            match arg.as_str() {
                "--help" | "-h" => usage(0),
                "--skip-validation" => skip_validation = true,
                _ => {
                    let value = args
                        .next()
                        .unwrap_or_else(|| fatal(&format!("missing value for {arg}")));
                    match arg.as_str() {
                        "--output" => output = Some(PathBuf::from(value)),
                        "--format" => format = parse_format(&value),
                        "--families" => config.families = parse_families(&value),
                        "--dims" => config.ring_dims = parse_csv(&value, "--dims"),
                        "--bounds" => {
                            config.coeff_linf_bounds = parse_csv(&value, "--bounds");
                        }
                        "--max-rank" => config.max_rank = parse(&value, "--max-rank"),
                        "--target-bits" => config.target_bits = parse(&value, "--target-bits"),
                        "--search-cap" => config.search_cap = Some(parse(&value, "--search-cap")),
                        "--progress-every" => {
                            config.progress_every = Some(parse(&value, "--progress-every"));
                        }
                        "--profile" => config.profile = parse_profile(&value),
                        _ => fatal(&format!("unknown argument {arg}")),
                    }
                }
            }
        }
        Self {
            config,
            output,
            format,
            skip_validation,
        }
    }
}

fn write_csv_rows(rows: &[InfinityWidthRow], output: Option<&PathBuf>) -> io::Result<()> {
    match output {
        Some(path) => {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            let mut file = fs::File::create(path)?;
            write_csv_rows_to(&mut file, rows)
        }
        None => {
            let stdout = io::stdout();
            let mut handle = stdout.lock();
            write_csv_rows_to(&mut handle, rows)
        }
    }
}

fn write_csv_rows_to(mut writer: impl Write, rows: &[InfinityWidthRow]) -> io::Result<()> {
    writeln!(writer, "{}", InfinityWidthRow::csv_header())?;
    for row in rows {
        writeln!(writer, "{}", row.to_csv_record())?;
    }
    Ok(())
}

fn write_rust_split(
    rows: &[InfinityWidthRow],
    config: &InfinityWidthTableConfig,
    output: Option<&Path>,
) -> io::Result<()> {
    let default_out_dir =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../akita-types/src/sis/generated_sis_table");
    let out_dir = output.unwrap_or(default_out_dir.as_path());
    fs::create_dir_all(out_dir)?;
    let min_security_bits =
        min_security_bits(config).expect("rust-split caller validates integer target bits");
    fs::write(out_dir.join("mod.rs"), rust_mod_source(min_security_bits))?;
    let arms = rust_table_arms(rows, config.max_rank);
    for family in [
        AkitaModulusFamily::Q32,
        AkitaModulusFamily::Q64,
        AkitaModulusFamily::Q128,
    ] {
        fs::write(
            out_dir.join(format!("{}.rs", family.label())),
            rust_family_source(family, arms.get(&family).map(Vec::as_slice).unwrap_or(&[])),
        )?;
    }
    Ok(())
}

fn rust_mod_source(min_security_bits: u16) -> String {
    format!(
        "{TABLE_HEADER}mod q128;\nmod q32;\nmod q64;\n\nuse super::SisModulusFamily;\n\n/// Generated SIS max-width table: for each `(security_floor, family, d, coeff_linf_bound)` the\n/// maximum secure ring-element width per module rank (`widths[rank - 1]`).\n#[rustfmt::skip]\npub(crate) fn sis_max_widths(\n    min_security_bits: u16,\n    family: SisModulusFamily,\n    d: u32,\n    coeff_linf_bound: u128,\n) -> Option<&'static [u64]> {{\n    if min_security_bits != {min_security_bits} {{\n        return None;\n    }}\n    match family {{\n        SisModulusFamily::Q32 => q32::sis_max_widths(d, coeff_linf_bound),\n        SisModulusFamily::Q64 => q64::sis_max_widths(d, coeff_linf_bound),\n        SisModulusFamily::Q128 => q128::sis_max_widths(d, coeff_linf_bound),\n    }}\n}}\n"
    )
}

fn rust_family_source(family: AkitaModulusFamily, arms: &[String]) -> String {
    let mut source = format!(
        "{TABLE_HEADER}// Family: {}\n\n#[rustfmt::skip]\npub(super) fn sis_max_widths(d: u32, coeff_linf_bound: u128) -> Option<&'static [u64]> {{\n    match (d, coeff_linf_bound) {{\n",
        family.label().to_uppercase()
    );
    for arm in arms {
        source.push_str("        ");
        source.push_str(arm);
        source.push('\n');
    }
    source.push_str("        _ => None,\n    }\n}\n");
    source
}

fn min_security_bits(config: &InfinityWidthTableConfig) -> Option<u16> {
    if config.target_bits.fract() == 0.0
        && config.target_bits >= 0.0
        && config.target_bits <= f64::from(u16::MAX)
    {
        Some(config.target_bits as u16)
    } else {
        None
    }
}

fn parse_families(raw: &str) -> Vec<AkitaModulusFamily> {
    raw.split(',')
        .filter(|value| !value.trim().is_empty())
        .map(|value| {
            AkitaModulusFamily::parse(value.trim())
                .unwrap_or_else(|error| fatal(&format!("invalid --families entry: {error}")))
        })
        .collect()
}

fn parse_csv<T>(raw: &str, field: &str) -> Vec<T>
where
    T: std::str::FromStr,
    T::Err: std::fmt::Debug,
{
    let values: Vec<T> = raw
        .split(',')
        .filter(|value| !value.trim().is_empty())
        .map(|value| parse(value.trim(), field))
        .collect();
    if values.is_empty() {
        fatal(&format!("{field} must not be empty"));
    }
    values
}

fn parse_profile(value: &str) -> InfinityWidthProfile {
    match value {
        "local-minimum" | "local_minimum" => InfinityWidthProfile::LocalMinimum,
        "exhaustive-serial" | "exhaustive_serial" => InfinityWidthProfile::ExhaustiveSerial,
        "exhaustive-parallel" | "exhaustive_parallel" => {
            #[cfg(not(feature = "parallel"))]
            fatal("profile exhaustive-parallel requires building with --features parallel");
            #[cfg(feature = "parallel")]
            {
                InfinityWidthProfile::ExhaustiveParallel
            }
        }
        _ => fatal("profile must be one of: local-minimum, exhaustive-serial, exhaustive-parallel"),
    }
}

fn parse_format(value: &str) -> OutputFormat {
    match value {
        "csv" => OutputFormat::Csv,
        "rust-split" | "rust_split" => OutputFormat::RustSplit,
        _ => fatal("--format must be one of: csv, rust-split"),
    }
}

fn parse<T>(value: &str, field: &str) -> T
where
    T: std::str::FromStr,
    T::Err: std::fmt::Debug,
{
    value
        .parse()
        .unwrap_or_else(|error| fatal(&format!("invalid {field}: {error:?}")))
}

fn usage(code: i32) -> ! {
    eprintln!(
        "usage: infinity_width_table [--output PATH] [--format csv|rust-split] [--families q32,q64,q128] [--dims 32,64,128,256] [--bounds B1,B2] [--max-rank N] [--target-bits BITS] [--search-cap N] [--profile local-minimum|exhaustive-serial|exhaustive-parallel] [--progress-every N] [--skip-validation]"
    );
    process::exit(code);
}

fn fatal(message: &str) -> ! {
    eprintln!("error: {message}");
    process::exit(2);
}
