#!/usr/bin/env bash

set -u
set -o pipefail

usage() {
    cat <<'EOF'
usage: scripts/check-rust-file-lines.sh [--max-lines N] [--baseline PATH] [--no-baseline]

Checks tracked Rust files against a physical line-count cap.

By default this enforces a 1500-line cap with the explicit ratchet baseline in
scripts/rust-file-line-cap-baseline.tsv. Baseline entries are not permanent
exemptions: they may not grow, and they must be removed once the file is under
the cap.

Machine-generated Rust files are exempt: any tracked file whose first physical
line begins with the marker comment "// Generated by " is skipped, since its
size is dictated by the emitter, not hand-authored. Hand-written files (which
lack the marker) are always checked, even when they live alongside generated
output.
EOF
}

# First-line marker the table/code emitters write at the top of every file they
# generate. Files carrying it are exempt from the line cap.
generated_marker_prefix='// Generated by '

max_lines="${AKITA_RUST_FILE_LINE_CAP:-1500}"
baseline_path="scripts/rust-file-line-cap-baseline.tsv"
use_baseline=true

while [ "$#" -gt 0 ]; do
    case "$1" in
        --max-lines)
            if [ "$#" -lt 2 ]; then
                echo "error: --max-lines requires a value" >&2
                exit 2
            fi
            max_lines="$2"
            shift 2
            ;;
        --baseline)
            if [ "$#" -lt 2 ]; then
                echo "error: --baseline requires a path" >&2
                exit 2
            fi
            baseline_path="$2"
            use_baseline=true
            shift 2
            ;;
        --no-baseline)
            use_baseline=false
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            echo "error: unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

case "$max_lines" in
    '' | *[!0-9]*)
        echo "error: max line count must be a positive integer, got: $max_lines" >&2
        exit 2
        ;;
esac

if [ "$max_lines" -le 0 ]; then
    echo "error: max line count must be positive, got: $max_lines" >&2
    exit 2
fi

repo_root="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$repo_root" ]; then
    echo "error: must be run inside a git repository" >&2
    exit 2
fi

cd "$repo_root" || exit 2

baseline_paths=()
baseline_counts=()
baseline_consumed=()
tracked_rust_paths=()
errors=0

record_error() {
    echo "error: $*" >&2
    errors=$((errors + 1))
}

physical_line_count() {
    awk 'END { print NR }' "$1"
}

# A file is generated (and thus cap-exempt) when its first physical line begins
# with the emitter marker comment.
is_generated_file() {
    local file="$1"
    local first_line=""
    IFS= read -r first_line < "$file" || true
    case "$first_line" in
        "$generated_marker_prefix"*)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

load_tracked_rust_paths() {
    local file
    while IFS= read -r -d '' file; do
        tracked_rust_paths+=("$file")
    done < <(git ls-files -z -- '*.rs')
}

tracked_rust_index() {
    local target="$1"
    local i=0
    while [ "$i" -lt "${#tracked_rust_paths[@]}" ]; do
        if [ "${tracked_rust_paths[$i]}" = "$target" ]; then
            echo "$i"
            return 0
        fi
        i=$((i + 1))
    done
    return 1
}

baseline_index() {
    local target="$1"
    local i=0
    while [ "$i" -lt "${#baseline_paths[@]}" ]; do
        if [ "${baseline_paths[$i]}" = "$target" ]; then
            echo "$i"
            return 0
        fi
        i=$((i + 1))
    done
    return 1
}

load_baseline() {
    local file="$1"
    local line_number=0
    local line count path existing

    if [ ! -f "$file" ]; then
        record_error "baseline file not found: $file"
        return
    fi

    while IFS= read -r line || [ -n "$line" ]; do
        line_number=$((line_number + 1))
        line="${line%$'\r'}"

        case "$line" in
            '' | '#'*)
                continue
                ;;
        esac

        if [ "$line" = "${line#*$'\t'}" ]; then
            record_error "$file:$line_number: expected '<line-count><TAB><path>'"
            continue
        fi

        count="${line%%$'\t'*}"
        path="${line#*$'\t'}"

        case "$count" in
            '' | *[!0-9]*)
                record_error "$file:$line_number: invalid line count: $count"
                continue
                ;;
        esac

        case "$path" in
            '' | /* | ../* | */../*)
                record_error "$file:$line_number: path must be repo-relative: $path"
                continue
                ;;
        esac

        case "$path" in
            *.rs)
                ;;
            *)
                record_error "$file:$line_number: baseline path is not a Rust file: $path"
                continue
                ;;
        esac

        if existing="$(baseline_index "$path")"; then
            record_error "$file:$line_number: duplicate baseline path also recorded with ${baseline_counts[$existing]} lines: $path"
            continue
        fi

        if ! tracked_rust_index "$path" >/dev/null; then
            record_error "$file:$line_number: baseline path is not an exact tracked Rust file: $path"
            continue
        fi

        baseline_paths+=("$path")
        baseline_counts+=("$count")
        baseline_consumed+=(false)
    done < "$file"
}

load_tracked_rust_paths

if [ "$use_baseline" = true ]; then
    load_baseline "$baseline_path"
fi

scanned=0
generated_skipped=0

for file in "${tracked_rust_paths[@]}"; do
    if is_generated_file "$file"; then
        generated_skipped=$((generated_skipped + 1))
        if idx="$(baseline_index "$file")"; then
            baseline_consumed[$idx]=true
            record_error "$file is machine-generated (cap-exempt); remove its baseline entry"
        fi
        continue
    fi

    scanned=$((scanned + 1))
    lines="$(physical_line_count "$file")"
    idx=""

    if idx="$(baseline_index "$file")"; then
        recorded="${baseline_counts[$idx]}"
        baseline_consumed[$idx]=true
    else
        recorded=""
    fi

    if [ "$lines" -gt "$max_lines" ]; then
        if [ -n "$recorded" ]; then
            if [ "$lines" -gt "$recorded" ]; then
                record_error "$file has $lines lines, above its baseline of $recorded lines and cap of $max_lines"
            fi
        else
            record_error "$file has $lines lines, above the cap of $max_lines"
        fi
    elif [ -n "$recorded" ]; then
        record_error "$file has $lines lines, at or below the cap of $max_lines; remove its baseline entry"
    fi
done

i=0
while [ "$i" -lt "${#baseline_paths[@]}" ]; do
    if [ "${baseline_consumed[$i]}" != true ]; then
        record_error "baseline path was not scanned as a tracked Rust file: ${baseline_paths[$i]}"
    fi
    i=$((i + 1))
done

if [ "$errors" -ne 0 ]; then
    cat >&2 <<EOF

Rust file line-cap check failed.

Split over-cap files into smaller modules. For current offenders listed in
$baseline_path, do not raise the recorded count. Remove the entry once the file
reaches the cap.
EOF
    exit 1
fi

echo "Rust file line-cap check passed: scanned $scanned tracked Rust files; cap=$max_lines; baseline_entries=${#baseline_paths[@]}; generated_exempt=$generated_skipped."
