#!/usr/bin/env python3
"""Regenerate and stitch `crates/akita-types/src/sis/generated_sis_linf_table/`."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from gen_sis_linf_table import (  # noqa: E402
    PINNED_LATTICE_ESTIMATOR_SHA,
    RING_DIMS,
    assert_pinned_estimator,
    COEFF_LINF_BUCKETS,
    cell_cache_path,
    default_cache_dir,
    read_cell_cache,
)

OUT_DIR = ROOT / "crates/akita-types/src/sis/generated_sis_linf_table"
GEN = ROOT / "scripts/gen_sis_linf_table.py"
ESTIMATOR = ROOT / "third_party/lattice-estimator"
FAMILIES = ("q32", "q64", "q128")
FAMILY_ENUM = {"q32": "Q32", "q64": "Q64", "q128": "Q128"}
ARM_RE = re.compile(r"^\((\d+), (\d+)\) => Some\(&\[(.*?)\]\),$")

TABLE_HEADER = f"""// AUTO-GENERATED by scripts/stitch_generated_sis_linf_table.py — do not edit by hand.
//
// SIS width thresholds for 128-bit security (ADPS16, coefficient L-infinity norm=oo).
// lattice-estimator: https://github.com/quangvdao/lattice-estimator.git @ {PINNED_LATTICE_ESTIMATOR_SHA}
// Keys: coefficient-Linf collision buckets B in `COEFF_LINF_BUCKETS` (`sis/ajtai_key.rs`).
//
// Regen:
//   git submodule update --init third_party/lattice-estimator
//   sage -python scripts/stitch_generated_sis_linf_table.py --jobs 6
//
// Incremental (while regen runs):
//   sage -python scripts/stitch_generated_sis_linf_table.py --from-cache --allow-partial
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jobs", type=int, default=6)
    parser.add_argument("--max-rank", type=int, default=20)
    parser.add_argument(
        "--family",
        choices=FAMILIES,
        action="append",
        help="Regen only these families (default: all). Repeatable.",
    )
    parser.add_argument(
        "--from-cache",
        action="store_true",
        help="Write .rs files from per-cell JSON cache (no Sage).",
    )
    parser.add_argument(
        "--cache-dir",
        default=None,
        help="Cell cache directory (default: <repo>/.sis_linf_cache).",
    )
    parser.add_argument(
        "--allow-partial",
        action="store_true",
        help="With --from-cache, emit rows for cached cells only.",
    )
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def resolve_cache_dir(args: argparse.Namespace) -> Path:
    return Path(args.cache_dir).expanduser() if args.cache_dir else default_cache_dir()


def widths_to_arm(d: int, collision: int, widths: list[int]) -> str:
    ws = ", ".join(f"{w:_}" for w in widths)
    return f"({d}, {collision}) => Some(&[{ws}]),"


def load_arms_from_cache(
    cache_dir: Path,
    family: str,
    max_rank: int,
    *,
    allow_partial: bool,
) -> tuple[list[str], int, int]:
    """Return (arm lines, cached cell count, expected cell count)."""
    arms: list[str] = []
    cached = 0
    expected = len(RING_DIMS) * len(COEFF_LINF_BUCKETS)
    for d in RING_DIMS:
        dead = False
        for collision in COEFF_LINF_BUCKETS:
            if dead:
                break
            path = cell_cache_path(cache_dir, family, d, collision)
            widths = read_cell_cache(path, max_rank)
            if widths is None:
                if allow_partial:
                    continue
                raise SystemExit(f"{family} missing cache cell d={d}, collision_linf={collision}")
            cached += 1
            if all(w == 0 for w in widths):
                dead = True
                continue
            arms.append(widths_to_arm(d, collision, widths))
    return arms, cached, expected


def run_family(family: str, jobs: int, max_rank: int, cache_dir: Path) -> str:
    cmd = [
        "sage",
        "-python",
        str(GEN),
        "--family",
        family,
        "--jobs",
        str(jobs),
        "--max-rank",
        str(max_rank),
        "--format",
        "rust",
        "--estimator-path",
        str(ESTIMATOR),
        "--cache-dir",
        str(cache_dir),
    ]
    print(f"running: {' '.join(cmd)}", file=sys.stderr)
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise SystemExit(f"{family} regen failed:\n{proc.stderr}")
    return proc.stdout


def parse_arms(block: str) -> dict[tuple[int, int], str]:
    arms: dict[tuple[int, int], str] = {}
    for line in block.splitlines():
        stripped = line.strip()
        match = ARM_RE.match(stripped)
        if match is None:
            continue
        d = int(match.group(1))
        collision = int(match.group(2))
        arms[(d, collision)] = stripped
    return arms


def validate_rank_count(family: str, arm_lines: list[str], max_rank: int) -> None:
    for arm in arm_lines:
        match = ARM_RE.match(arm)
        if match is None:
            continue
        count = 0 if not match.group(3) else len(match.group(3).split(","))
        if count != max_rank:
            raise SystemExit(
                f"{family} row (d={match.group(1)}, collision_linf={match.group(2)}) "
                f"has {count} widths; expected --max-rank {max_rank}"
            )


def stitch_family_file(family: str, arm_lines: list[str]) -> str:
    enum_name = FAMILY_ENUM[family]
    parts = [
        TABLE_HEADER,
        f"// Family: {enum_name}\n\n",
        "#[rustfmt::skip]\n",
        "pub(super) fn sis_max_widths(d: u32, collision_linf: u128) -> Option<&'static [u64]> {\n",
        "    match (d, collision_linf) {\n",
    ]
    for arm in arm_lines:
        parts.append(f"        {arm}\n")
    parts.append("        _ => None,\n")
    parts.append("    }\n")
    parts.append("}\n")
    return "".join(parts)


def stitch_mod() -> str:
    parts = [
        TABLE_HEADER,
        "\nmod q128;\nmod q32;\nmod q64;\n\n",
        "use super::SisModulusFamily;\n\n",
        "/// Generated coefficient-Linf SIS max-width table.\n",
        "#[rustfmt::skip]\n",
        "pub(crate) fn sis_max_widths(\n",
        "    family: SisModulusFamily,\n",
        "    d: u32,\n",
        "    collision_linf: u128,\n",
        ") -> Option<&'static [u64]> {\n",
        "    match family {\n",
        "        SisModulusFamily::Q32 => q32::sis_max_widths(d, collision_linf),\n",
        "        SisModulusFamily::Q64 => q64::sis_max_widths(d, collision_linf),\n",
        "        SisModulusFamily::Q128 => q128::sis_max_widths(d, collision_linf),\n",
        "    }\n",
        "}\n",
    ]
    return "".join(parts)


def write_table(family_arm_lines: dict[str, list[str]], *, dry_run: bool) -> None:
    if dry_run:
        print(stitch_mod())
        for family in sorted(family_arm_lines):
            print(stitch_family_file(family, family_arm_lines[family]))
        return

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "mod.rs").write_text(stitch_mod())
    for family in sorted(family_arm_lines):
        path = OUT_DIR / f"{family}.rs"
        path.write_text(stitch_family_file(family, family_arm_lines[family]))
        print(f"wrote {path} ({path.stat().st_size:,} bytes)", file=sys.stderr)


def main() -> None:
    args = parse_args()
    assert_pinned_estimator(ESTIMATOR)
    cache_dir = resolve_cache_dir(args)
    families = tuple(args.family) if args.family else FAMILIES
    family_arm_lines: dict[str, list[str]] = {}

    if args.from_cache:
        for family in families:
            arms, cached, expected = load_arms_from_cache(
                cache_dir,
                family,
                args.max_rank,
                allow_partial=args.allow_partial,
            )
            if not arms and not args.allow_partial:
                raise SystemExit(f"{family}: no cached cells in {cache_dir / family}")
            family_arm_lines[family] = arms
            validate_rank_count(family, arms, args.max_rank)
            print(
                f"{family}: {cached}/{expected} cells cached, {len(arms)} table rows",
                file=sys.stderr,
            )
    else:
        for family in families:
            block = run_family(family, args.jobs, args.max_rank, cache_dir)
            arms = parse_arms(block)
            expected = {(d, b) for d in RING_DIMS for b in COEFF_LINF_BUCKETS}
            missing = sorted(expected - set(arms))
            if missing:
                raise SystemExit(f"{family} missing {len(missing)} rows, first: {missing[0]}")
            family_arm_lines[family] = [arms[key] for key in sorted(arms)]
            validate_rank_count(family, family_arm_lines[family], args.max_rank)

    if args.dry_run:
        write_table(family_arm_lines, dry_run=True)
        return

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if family_arm_lines.keys() == set(FAMILIES):
        (OUT_DIR / "mod.rs").write_text(stitch_mod())
    elif not (OUT_DIR / "mod.rs").exists():
        (OUT_DIR / "mod.rs").write_text(stitch_mod())

    for family in families:
        path = OUT_DIR / f"{family}.rs"
        path.write_text(stitch_family_file(family, family_arm_lines[family]))
        print(f"wrote {path} ({path.stat().st_size:,} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
