#!/usr/bin/env python3
"""Regenerate and stitch `crates/akita-types/src/sis/generated_sis_table.rs`."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "crates/akita-types/src/sis/generated_sis_table.rs"
GEN = ROOT / "scripts/gen_sis_table.py"
FAMILIES = ("q32", "q64", "q128")
FAMILY_ENUM = {"q32": "Q32", "q64": "Q64", "q128": "Q128"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jobs", type=int, default=6)
    parser.add_argument("--max-rank", type=int, default=20)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def run_family(family: str, jobs: int, max_rank: int) -> str:
    cmd = [
        "sage",
        "-python",
        str(GEN),
        "--family",
        family,
        "--jobs",
        str(jobs),
        "--max-rank",
        str(max_rank),
        "--format",
        "rust",
    ]
    print(f"running: {' '.join(cmd)}", file=sys.stderr)
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise SystemExit(f"{family} regen failed:\n{proc.stderr}")
    return proc.stdout


def stitch(family_blocks: dict[str, str]) -> str:
    header = """// AUTO-GENERATED by scripts/stitch_generated_sis_table.py — do not edit by hand.
//
// SIS width thresholds for 128-bit security (BDGL16, Euclidean norm=2).
// Per-ring-row squared collision keys are exact powers of two (see
// `MIN_LOG_BUCKET` / `MAX_LOG_BUCKET` in `sis/ajtai_key.rs`).
//
// Regen:
//   git submodule update --init third_party/lattice-estimator
//   sage -python scripts/stitch_generated_sis_table.py --jobs 6

use super::SisModulusFamily;

/// Generated SIS max-width table: for each `(family, d, collision_l2_sq)` the
/// maximum secure ring-element width per module rank (`widths[rank - 1]`).
#[rustfmt::skip]
pub(crate) fn sis_max_widths(
    family: SisModulusFamily,
    d: u32,
    collision_l2_sq: u128,
) -> Option<&'static [u64]> {
    match family {
"""
    parts = [header]
    for family in FAMILIES:
        enum_name = FAMILY_ENUM[family]
        block = family_blocks[family]
        # Drop per-family provenance comments; keep only match arms.
        arms: list[str] = []
        for line in block.splitlines():
            stripped = line.strip()
            if stripped.startswith("(") and "=> Some" in stripped:
                arms.append(f"            {stripped}")
        parts.append(f"        SisModulusFamily::{enum_name} => match (d, collision_l2_sq) {{\n")
        parts.extend(f"{arm}\n" for arm in arms)
        parts.append("            _ => None,\n")
        parts.append("        },\n")
    parts.append("    }\n}\n")
    return "".join(parts)


def main() -> None:
    args = parse_args()
    blocks = {fam: run_family(fam, args.jobs, args.max_rank) for fam in FAMILIES}
    content = stitch(blocks)
    if args.dry_run:
        print(content)
        return
    OUT.write_text(content)
    print(f"wrote {OUT} ({len(content):,} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
