#!/usr/bin/env python3
"""Regenerate and stitch the ADPS16 Euclidean SIS table."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from gen_sis_table import PINNED_LATTICE_ESTIMATOR_SHA, assert_pinned_estimator  # noqa: E402

OUT_DIR = ROOT / "crates/akita-types/src/sis/generated_l2_sis_table"
GEN = ROOT / "scripts/gen_sis_table.py"
ESTIMATOR = ROOT / "third_party/lattice-estimator"
FAMILIES = ("q32", "q64", "q128")
FAMILY_ENUM = {"q32": "Q32", "q64": "Q64", "q128": "Q128"}
ARM_RE = re.compile(r"^\((\d+), (\d+)\) => Some\(&\[(.*?)\]\),$")

TABLE_HEADER = f"""// AUTO-GENERATED by scripts/stitch_generated_sis_table.py — do not edit by hand.
//
// SIS width thresholds for 128-bit quantum security (ADPS16, Euclidean norm=2).
// lattice-estimator: https://github.com/malb/lattice-estimator.git @ {PINNED_LATTICE_ESTIMATOR_SHA}
// Keys are whole-vector squared L2 collision bounds on a power-of-two ladder.
//
// Regen (full):
//   git submodule update --init third_party/lattice-estimator
//   sage -python scripts/stitch_generated_sis_table.py --jobs 6
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jobs", type=int, default=6)
    parser.add_argument("--max-rank", type=int, default=20)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def run_family(
    family: str,
    jobs: int,
    max_rank: int,
) -> str:
    cmd = [
        "sage",
        "-python",
        str(GEN),
        "--family",
        family,
        "--jobs",
        str(jobs),
        "--max-rank",
        str(max_rank),
        "--format",
        "rust",
        "--estimator-path",
        str(ESTIMATOR),
    ]
    print(f"running: {' '.join(cmd)}", file=sys.stderr)
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise SystemExit(f"{family} regen failed:\n{proc.stderr}")
    return proc.stdout


def parse_arms(block: str) -> dict[tuple[int, int], str]:
    arms: dict[tuple[int, int], str] = {}
    for line in block.splitlines():
        stripped = line.strip()
        match = ARM_RE.match(stripped)
        if match is None:
            continue
        d = int(match.group(1))
        collision = int(match.group(2))
        arms[(d, collision)] = stripped
    return arms


def validate_rank_count(family: str, arm_lines: list[str], max_rank: int) -> None:
    for arm in arm_lines:
        match = ARM_RE.match(arm)
        if match is None:
            continue
        count = 0 if not match.group(3) else len(match.group(3).split(","))
        if count != max_rank:
            raise SystemExit(
                f"{family} row (d={match.group(1)}, collision={match.group(2)}) "
                f"has {count} widths; expected --max-rank {max_rank}"
            )


def stitch_family_file(family: str, arm_lines: list[str]) -> str:
    enum_name = FAMILY_ENUM[family]
    parts = [
        TABLE_HEADER,
        f"// Family: {enum_name}\n\n",
        "#[rustfmt::skip]\n",
        "pub(super) fn sis_max_widths(d: u32, collision_l2_sq: u128) -> Option<&'static [u64]> {\n",
        "    match (d, collision_l2_sq) {\n",
    ]
    for arm in arm_lines:
        parts.append(f"        {arm}\n")
    parts.append("        _ => None,\n")
    parts.append("    }\n")
    parts.append("}\n")
    return "".join(parts)


def stitch_mod() -> str:
    parts = [
        TABLE_HEADER,
        "\nmod q128;\nmod q32;\nmod q64;\n\n",
        "use super::SisModulusProfileId;\n\n",
        "/// Generated SIS max-width table: for each `(family, d, collision_l2_sq)` the\n",
        "/// maximum secure ring-element width per module rank (`widths[rank - 1]`).\n",
        "#[rustfmt::skip]\n",
        "pub(crate) fn sis_max_widths(\n",
        "    family: SisModulusProfileId,\n",
        "    d: u32,\n",
        "    collision_l2_sq: u128,\n",
        ") -> Option<&'static [u64]> {\n",
        "    match family {\n",
        "        SisModulusProfileId::Q32Offset99 => q32::sis_max_widths(d, collision_l2_sq),\n",
        "        SisModulusProfileId::Q64Offset59 => q64::sis_max_widths(d, collision_l2_sq),\n",
        "        SisModulusProfileId::Q128OffsetA7F7 => q128::sis_max_widths(d, collision_l2_sq),\n",
        "    }\n",
        "}\n",
    ]
    return "".join(parts)


def write_table(family_arm_lines: dict[str, list[str]], *, dry_run: bool) -> None:
    if dry_run:
        print(stitch_mod())
        for family in FAMILIES:
            print(stitch_family_file(family, family_arm_lines[family]))
        return

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "mod.rs").write_text(stitch_mod())
    for family in FAMILIES:
        path = OUT_DIR / f"{family}.rs"
        path.write_text(stitch_family_file(family, family_arm_lines[family]))
        print(f"wrote {path} ({path.stat().st_size:,} bytes)", file=sys.stderr)


def main() -> None:
    args = parse_args()
    assert_pinned_estimator(ESTIMATOR)

    family_arm_lines: dict[str, list[str]] = {}
    for family in FAMILIES:
        block = run_family(family, args.jobs, args.max_rank)
        arms = parse_arms(block)
        family_arm_lines[family] = [arms[key] for key in sorted(arms)]
        validate_rank_count(family, family_arm_lines[family], args.max_rank)

    write_table(family_arm_lines, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
