#!/usr/bin/env python3
"""Regenerate and stitch `crates/akita-types/src/sis/generated_sis_table.rs`."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from gen_sis_table import RING_DIMS, derived_l2_collision_keys  # noqa: E402
OUT = ROOT / "crates/akita-types/src/sis/generated_sis_table.rs"
GEN = ROOT / "scripts/gen_sis_table.py"
FAMILIES = ("q32", "q64", "q128")
FAMILY_ENUM = {"q32": "Q32", "q64": "Q64", "q128": "Q128"}
ARM_RE = re.compile(r"^\((\d+), (\d+)\) => Some\(&\[(.*?)\]\),$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jobs", type=int, default=6)
    parser.add_argument("--max-rank", type=int, default=20)
    parser.add_argument(
        "--supplement-derived-only",
        action="store_true",
        help=(
            "Regenerate only derived d·B² rows and merge into the existing "
            "generated_sis_table.rs (skip the full power-of-two sweep)."
        ),
    )
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def run_family(
    family: str,
    jobs: int,
    max_rank: int,
    *,
    collisions: list[int] | None = None,
) -> str:
    cmd = [
        "sage",
        "-python",
        str(GEN),
        "--family",
        family,
        "--jobs",
        str(jobs),
        "--max-rank",
        str(max_rank),
        "--format",
        "rust",
    ]
    if collisions is not None:
        cmd.extend(
            [
                "--dims",
                ",".join(str(d) for d in RING_DIMS),
                "--collisions",
                ",".join(str(c) for c in collisions),
            ]
        )
    print(f"running: {' '.join(cmd)}", file=sys.stderr)
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise SystemExit(f"{family} regen failed:\n{proc.stderr}")
    return proc.stdout


def parse_arms(block: str) -> dict[tuple[int, int], str]:
    arms: dict[tuple[int, int], str] = {}
    for line in block.splitlines():
        stripped = line.strip()
        match = ARM_RE.match(stripped)
        if match is None:
            continue
        d = int(match.group(1))
        collision = int(match.group(2))
        arms[(d, collision)] = stripped
    return arms


def parse_existing_family_arms(content: str, family: str) -> dict[tuple[int, int], str]:
    enum_name = FAMILY_ENUM[family]
    marker = f"SisModulusFamily::{enum_name} => match (d, collision_l2_sq) {{"
    start = content.index(marker)
    end = content.index("_ => None,", start)
    block = content[start:end]
    return parse_arms(block)


def merge_family_blocks(
    pow2_block: str | None,
    derived_block: str,
    existing: dict[tuple[int, int], str] | None = None,
) -> list[str]:
    merged: dict[tuple[int, int], str] = {}
    if existing is not None:
        merged.update(existing)
    if pow2_block is not None:
        merged.update(parse_arms(pow2_block))
    merged.update(parse_arms(derived_block))
    return [merged[key] for key in sorted(merged)]


def stitch(family_arm_lines: dict[str, list[str]]) -> str:
    header = """// AUTO-GENERATED by scripts/stitch_generated_sis_table.py — do not edit by hand.
//
// SIS width thresholds for 128-bit security (BDGL16, Euclidean norm=2).
// Keys are the union of:
//   - power-of-two squared-collision buckets (2^MIN_LOG_BUCKET .. 2^MAX_LOG_BUCKET)
//   - derived keys K = d · B² for coefficient-L∞ buckets B (norm_bound default)
// See `MIN_LOG_BUCKET` / `MAX_LOG_BUCKET` / `COEFF_LINF_BUCKETS` in `sis/ajtai_key.rs`.
//
// Regen (full):
//   git submodule update --init third_party/lattice-estimator
//   sage -python scripts/stitch_generated_sis_table.py --jobs 6
//
// Regen derived rows only (merge into existing table):
//   sage -python scripts/stitch_generated_sis_table.py --supplement-derived-only --jobs 6

use super::SisModulusFamily;

/// Generated SIS max-width table: for each `(family, d, collision_l2_sq)` the
/// maximum secure ring-element width per module rank (`widths[rank - 1]`).
#[rustfmt::skip]
pub(crate) fn sis_max_widths(
    family: SisModulusFamily,
    d: u32,
    collision_l2_sq: u128,
) -> Option<&'static [u64]> {
    match family {
"""
    parts = [header]
    for family in FAMILIES:
        enum_name = FAMILY_ENUM[family]
        parts.append(f"        SisModulusFamily::{enum_name} => match (d, collision_l2_sq) {{\n")
        for arm in family_arm_lines[family]:
            parts.append(f"            {arm}\n")
        parts.append("            _ => None,\n")
        parts.append("        },\n")
    parts.append("    }\n}\n")
    return "".join(parts)


def main() -> None:
    args = parse_args()
    derived_keys = derived_l2_collision_keys()
    existing_content = OUT.read_text() if OUT.exists() else None

    family_arm_lines: dict[str, list[str]] = {}
    for family in FAMILIES:
        derived_block = run_family(
            family, args.jobs, args.max_rank, collisions=derived_keys
        )
        if args.supplement_derived_only:
            if existing_content is None:
                raise SystemExit(f"missing existing table at {OUT}")
            existing_arms = parse_existing_family_arms(existing_content, family)
            family_arm_lines[family] = merge_family_blocks(
                None, derived_block, existing=existing_arms
            )
        else:
            pow2_block = run_family(family, args.jobs, args.max_rank)
            family_arm_lines[family] = merge_family_blocks(pow2_block, derived_block)

    content = stitch(family_arm_lines)
    if args.dry_run:
        print(content)
        return
    OUT.write_text(content)
    print(f"wrote {OUT} ({len(content):,} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
