name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**", main]
  schedule:
    - cron: "17 8 * * 1"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    name: Cargo deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1
      - uses: EmbarkStudios/cargo-deny-action@08f29ebbc9295095546acaf37220058f628a4720 # v2
        with:
          command: check bans licenses sources advisories

  cargo-audit:
    name: Cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1
      - name: Install cargo-audit
        uses: taiki-e/install-action@50414676f9f5d50a65992c6dd2ed02641263226c # cargo-audit
        with:
          tool: cargo-audit
      - name: Check RustSec advisories
        run: cargo audit
